### ISSUE TITLE
MW 1.34+, use DB_REPLICA

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticApprovedRevs#11]
### Setup and configuration

- SMW version: 3.1.0
- SAR version: 1.0.0-alpha
- MW version: 1.31+

### Issue

Identical to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4093

**Comment by mwjames** [comment]
I think when examining the CI output, you'll see that the issue in not
related to SMW or SAR invoked code but because of ApprovedRevs not
being tagged with an appropriate version, version 1.0 it is throwing
the error, so unless this is fixed in ApprovedRevs there is nothing we
can do here.
