### ISSUE TITLE
File approval and file ingestion (`ElasticStore`)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticApprovedRevs#2]
### Setup and configuration

- SMW version: any
- SAR version: any

### Issue

When using the `ElasticStore` with the enabled file ingest option and a specific file version gets approved, support the reindexing (ingestion) of the approved file so that the correct (i.e. approved) file version (sha1) is indexed.

**Comment by kghbln** [comment]
@mwjames I do not think that this is a holdup for #3  and could very well roll into a 1.1.0 release?
