### ISSUE TITLE
Get I18n via translatwiki rolling

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticApprovedRevs#8]
- [x] 1) Add repo to user group with push rights - 2019-07-27
- [x] 2) Review "en.json" and extend "qqq.json" - 2019-07-29 #10 
- [x] 3) Create pull to add extension to twn - 2019-07-30

**Comment by krabina** [comment]
I would happily provide a German translation one it is on translatewiki. Or should I do a de.json?

**Comment by kghbln** [comment]
> Or should I do a de.json?

@krabina This is not necessary and will be overridden anyways. However rather extend "qqq.json" which is a requirement for this to get rolling. This will be great. I would do do 3) afterwards.

**Comment by kghbln** [comment]
Ad 3) https://gerrit.wikimedia.org/r/#/c/translatewiki/+/526259/

**Comment by Abijeet** [comment]
Merged and deployed patch on Translatewiki.net

Fixed the extension URL in the qqq.json file on Translatewiki.net - https://github.com/SemanticMediaWiki/SemanticApprovedRevs/blob/master/i18n/qqq.json#L8

**Comment by kghbln** [comment]
@Abijeet Cool. Thanks a lot!

**Comment by krabina** [comment]
I have just provided a [German translation](https://translatewiki.net/wiki/Special:Translate/mwgithub-semanticapprovedrevs?group=mwgithub-semanticapprovedrevs&language=de&action=proofread&filter=translated).
